#!/bin/bash
# Setup script for CD deployment to Alpine container

set -e

echo "==============================================="
echo "GitHub Actions CD Setup for whitelist-api"
echo "==============================================="
echo ""

echo "Step 1: Push the workflow file"
echo "-------------------------------"
echo "The workflow file has been created at:"
echo ".github/workflows/deploy-api.yml"
echo ""
echo "You need to push it with a token that has 'workflow' scope."
echo ""
echo "Option A: Use GitHub CLI"
echo "  gh auth refresh -s workflow"
echo "  git push"
echo ""
echo "Option B: Use Personal Access Token"
echo "  1. Go to: https://github.com/settings/tokens"
echo "  2. Generate new token with 'workflow' scope"
echo "  3. git remote set-url origin https://YOUR_TOKEN@github.com/balejosg/whitelist.git"
echo "  4. git push"
echo ""
read -p "Press Enter when you've pushed the workflow file..."

echo ""
echo "Step 2: Generate SSH key on Alpine container"
echo "----------------------------------------------"
echo "Run these commands ON THE ALPINE CONTAINER (CT102):"
echo ""
echo "ssh-keygen -t ed25519 -C 'github-actions-deploy' -f ~/.ssh/github_actions_deploy -N ''"
echo "cat ~/.ssh/github_actions_deploy.pub >> ~/.ssh/authorized_keys"
echo "chmod 600 ~/.ssh/authorized_keys"
echo ""
read -p "Press Enter when done..."

echo ""
echo "Step 3: Copy the private key"
echo "-----------------------------"
echo "Run this command ON THE ALPINE CONTAINER:"
echo ""
echo "cat ~/.ssh/github_actions_deploy"
echo ""
echo "Copy the ENTIRE output (including -----BEGIN and -----END lines)"
read -p "Press Enter when you have copied the key..."

echo ""
echo "Step 4: Add GitHub Secrets"
echo "--------------------------"
echo "Go to: https://github.com/balejosg/whitelist/settings/secrets/actions"
echo ""
echo "Add these 4 secrets:"
echo ""
echo "1. DEPLOY_HOST"
echo "   Value: whitelist-api.duckdns.org"
echo ""
echo "2. DEPLOY_USER"
echo "   Value: whitelist-api"
echo ""
echo "3. DEPLOY_SSH_KEY"
echo "   Value: Paste the entire private key from Step 3"
echo ""
echo "4. DEPLOY_PORT"
echo "   Value: 22"
echo ""
read -p "Press Enter when all secrets are added..."

echo ""
echo "Step 5: Test the deployment"
echo "----------------------------"
echo "Make a small change to test:"
echo ""
echo "echo '# Test deployment' >> whitelist-request-api/README.md"
echo "git add whitelist-request-api/README.md"
echo "git commit -m 'Test: trigger CD deployment'"
echo "git push"
echo ""
echo "Then watch the deployment at:"
echo "https://github.com/balejosg/whitelist/actions"
echo ""
echo "✅ Setup complete!"
