name: 'Docker Build and Push'
description: 'Build and optionally push Docker image with caching'

inputs:
  image-name:
    description: 'Image name (e.g., dashboard, api)'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  context:
    description: 'Build context path'
    required: false
    default: '.'
  platforms:
    description: 'Target platforms (comma-separated)'
    required: false
    default: 'linux/amd64'
  push:
    description: 'Whether to push the image'
    required: false
    default: 'false'
  registry:
    description: 'Container registry'
    required: false
    default: 'ghcr.io'

outputs:
  tags:
    description: 'Generated image tags'
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: 'Generated image labels'
    value: ${{ steps.meta.outputs.labels }}
  digest:
    description: 'Image digest (if pushed)'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
